spring:
  # database info
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/tiny_url?useSSL=false
    username: root
    password: xxx
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # redis
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 1
      host: 127.0.0.1
      port: 6379
      password: xxx

tiny-url-app:
  # reference fun.powercheng.url.tiny.enums.ShortenerTypeEnum
  shortener-type: MURMUR32_WITH_BASE62
  # 如果用 UNIQUE_ID_WITH_BASE62 必须配置 worker id
  worker-id: 1
  # global cache config
  cache-config:
    cache-duration: 3
    duration-unit: hours